/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_tylercruz;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Tyler C
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_createPerson = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_Apellido = new javax.swing.JTextField();
        rb_Male = new javax.swing.JRadioButton();
        rb_Female = new javax.swing.JRadioButton();
        jt_Edad = new javax.swing.JTextField();
        jt_Vocacion = new javax.swing.JTextField();
        rb_TrueU = new javax.swing.JRadioButton();
        rb_FalseU = new javax.swing.JRadioButton();
        rb_TrueC = new javax.swing.JRadioButton();
        rb_FalseC = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jt_Name = new javax.swing.JTextField();
        jb_AddTree_Persona = new javax.swing.JButton();
        jt_Nacionalidad = new javax.swing.JTextField();
        jd_createPais = new javax.swing.JDialog();
        PanelPais = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jt_NamePais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdate_FechaFundacion = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jt_nameHimno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jb_Color = new javax.swing.JButton();
        jb_AddTree_Pais = new javax.swing.JButton();
        Sex = new javax.swing.ButtonGroup();
        TituloU = new javax.swing.ButtonGroup();
        CoronaVirus = new javax.swing.ButtonGroup();
        Menu_Personas = new javax.swing.JPopupMenu();
        jmi_AggPersona = new javax.swing.JMenuItem();
        Menu_Sex = new javax.swing.JPopupMenu();
        jmi_Hombre = new javax.swing.JMenuItem();
        jmi_Mujer = new javax.swing.JMenuItem();
        Menu_mod_elim = new javax.swing.JPopupMenu();
        jmi_ElimPersona = new javax.swing.JMenuItem();
        jmi_ModPersona = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Normal = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Corona = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Males = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_Females = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_Paises = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Agg_Pais = new javax.swing.JMenuItem();
        Agg_Persona = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nacionalidad:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Edad:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Genero:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Vocacion:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Titulo Universitario:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("CoronaVirus:");

        Sex.add(rb_Male);
        rb_Male.setText("M");

        Sex.add(rb_Female);
        rb_Female.setText("F");

        jt_Vocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_VocacionActionPerformed(evt);
            }
        });

        TituloU.add(rb_TrueU);
        rb_TrueU.setText("True");

        TituloU.add(rb_FalseU);
        rb_FalseU.setText("False");

        CoronaVirus.add(rb_TrueC);
        rb_TrueC.setText("True");

        CoronaVirus.add(rb_FalseC);
        rb_FalseC.setText("False");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Name:");

        jb_AddTree_Persona.setText("Add to List");
        jb_AddTree_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AddTree_PersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_createPersonLayout = new javax.swing.GroupLayout(jd_createPerson.getContentPane());
        jd_createPerson.getContentPane().setLayout(jd_createPersonLayout);
        jd_createPersonLayout.setHorizontalGroup(
            jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_createPersonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_createPersonLayout.createSequentialGroup()
                        .addComponent(jb_AddTree_Persona)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_createPersonLayout.createSequentialGroup()
                        .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_Nacionalidad))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_Name))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_Vocacion))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Female))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_TrueU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_FalseU))
                            .addGroup(jd_createPersonLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_TrueC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_FalseC)))
                        .addGap(59, 236, Short.MAX_VALUE))))
        );
        jd_createPersonLayout.setVerticalGroup(
            jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_createPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_Male)
                    .addComponent(rb_Female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_Vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_TrueU)
                    .addComponent(rb_FalseU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rb_TrueC)
                    .addComponent(rb_FalseC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_createPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jb_AddTree_Persona)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Name:");

        jt_NamePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NamePaisActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Date Fundacion:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Name Himno:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Color:");

        jb_Color.setText("Color");
        jb_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ColorActionPerformed(evt);
            }
        });

        jb_AddTree_Pais.setText("Add to Tree and List");
        jb_AddTree_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AddTree_PaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPaisLayout = new javax.swing.GroupLayout(PanelPais);
        PanelPais.setLayout(PanelPaisLayout);
        PanelPaisLayout.setHorizontalGroup(
            PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPaisLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_AddTree_Pais)
                    .addGroup(PanelPaisLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_Color))
                    .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelPaisLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jt_nameHimno))
                        .addGroup(PanelPaisLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jdate_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelPaisLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jt_NamePais, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        PanelPaisLayout.setVerticalGroup(
            PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPaisLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_NamePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jdate_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_nameHimno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jb_Color))
                .addGap(18, 18, 18)
                .addComponent(jb_AddTree_Pais)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_createPaisLayout = new javax.swing.GroupLayout(jd_createPais.getContentPane());
        jd_createPais.getContentPane().setLayout(jd_createPaisLayout);
        jd_createPaisLayout.setHorizontalGroup(
            jd_createPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_createPaisLayout.setVerticalGroup(
            jd_createPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmi_AggPersona.setText("Agg  Habitantes");
        jmi_AggPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AggPersonaActionPerformed(evt);
            }
        });
        Menu_Personas.add(jmi_AggPersona);

        jmi_Hombre.setText("Add Male");
        jmi_Hombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_HombreMouseClicked(evt);
            }
        });
        jmi_Hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_HombreActionPerformed(evt);
            }
        });
        Menu_Sex.add(jmi_Hombre);

        jmi_Mujer.setText("Add Female");
        jmi_Mujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_MujerMouseClicked(evt);
            }
        });
        jmi_Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_MujerActionPerformed(evt);
            }
        });
        Menu_Sex.add(jmi_Mujer);

        jmi_ElimPersona.setText("EliminarHabitante");
        jmi_ElimPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ElimPersonaActionPerformed(evt);
            }
        });
        Menu_mod_elim.add(jmi_ElimPersona);

        jmi_ModPersona.setText("Modificar Habitante");
        jmi_ModPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ModPersonaActionPerformed(evt);
            }
        });
        Menu_mod_elim.add(jmi_ModPersona);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_Normal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_NormalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Normal);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_Corona.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_Corona);

        jl_Males.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_Males);

        jl_Females.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_Females);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Males");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Females");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("Paises");

        jl_Paises.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_Paises);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Normales");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Normales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addGap(0, 87, Short.MAX_VALUE))
        );

        jMenu1.setText("Create");

        Agg_Pais.setText("Create Pais");
        Agg_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agg_PaisActionPerformed(evt);
            }
        });
        jMenu1.add(Agg_Pais);

        Agg_Persona.setText("Create Persona");
        Agg_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agg_PersonaActionPerformed(evt);
            }
        });
        jMenu1.add(Agg_Persona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NamePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NamePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NamePaisActionPerformed

    private void jb_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ColorActionPerformed
        // TODO add your handling code here:
        jb_Color.setForeground(JColorChooser.showDialog(this, "Eliga el color: ", Color.yellow));
        color = jb_Color.getForeground();
    }//GEN-LAST:event_jb_ColorActionPerformed

    private void Agg_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agg_PaisActionPerformed
        // TODO add your handling code here:
        jd_createPais.setModal(true);
        jd_createPais.pack();
        jd_createPais.setLocationRelativeTo(this);
        jd_createPais.setVisible(true);
    }//GEN-LAST:event_Agg_PaisActionPerformed

    private void jb_AddTree_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AddTree_PersonaActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) jl_Males.getModel();
        DefaultListModel modelo1
                = (DefaultListModel) jl_Females.getModel();
        int edad = Integer.parseInt(this.jt_Edad.getText());
        String sex = "";
        boolean title = true;
        boolean corona = true;
        if (this.rb_Male.isSelected()) {
            sex = "male";
        } else {
            sex = "female";
        }
        if (this.rb_TrueU.isSelected()) {
            title = true;
        } else {
            title = false;
        }
        if (this.rb_TrueC.isSelected()) {
            corona = true;
        } else {
            corona = false;
        }
        //String nacionalidad, String name, String apellido, int edad, String genero, String vocacion, boolean tituloU, boolean virus
        Persona x = new Persona(this.jt_Nacionalidad.getText(), this.jt_Name.getText(), this.jt_Apellido.getText(), edad, sex, this.jt_Vocacion.getText(),
                title, corona);
        if (sex.equals("male")) {
            modelo.addElement(x);
        } else {
            modelo1.addElement(x);
        }
        this.jt_Apellido.setText("");
        this.jt_Edad.setText("");
        this.jt_Nacionalidad.setText("");
        this.jt_Name.setText("");
        this.jt_Vocacion.setText("");
    }//GEN-LAST:event_jb_AddTree_PersonaActionPerformed

    private void jb_AddTree_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AddTree_PaisActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) jl_Paises.getModel();

        DefaultTreeModel m = (DefaultTreeModel) jt_Normal.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        String namePais = "", nombre = "";
        namePais = this.jt_NamePais.getText();
        nombre = this.jt_Edad.getText();
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().
                    equals(namePais)) {

                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode( //String name, Date fundacion, String nombreHimno, Color colorBandera
                        //new Pais(namePais,this.jdate_FechaFundacion.getDate(),this.jt_nameHimno.getText(),color)
                        //DefaultMutableTreeNode male = new DefaultMutableTreeNode()
                        //new Male()
                        //String name = JOptionPane.showInputDialog("Ingrese")
                        //p.add(new DefaultMutableTreeNode("Male"))
                        );
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            } //fin if
        } //fin for 
        if (centinela == -1) {
            DefaultMutableTreeNode n
                    = new DefaultMutableTreeNode(namePais);
            DefaultMutableTreeNode p
                    = new DefaultMutableTreeNode( //new Person(nombre)
                    //new Pais(namePais,this.jdate_FechaFundacion.getDate(),this.jt_nameHimno.getText(),color)
                    );
            n.add(p);
            raiz.add(n);
        }  // fin if          
        m.reload();
        modelo.addElement(namePais);
        this.jt_NamePais.setText("");
        this.jt_nameHimno.setText("");


    }//GEN-LAST:event_jb_AddTree_PaisActionPerformed

    private void jmi_AggPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AggPersonaActionPerformed
        // TODO add your handling code here:
        if (jl_Males.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_Normal.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_Males.getModel();
            String nacionalidad, nombre,apellido;
            int edad;
            nacionalidad
                    = ((Persona) modeloLISTA.get(
                            jl_Males.getSelectedIndex())).
                            getNacionalidad();

            nombre = ((Persona) modeloLISTA.get(
                    jl_Males.getSelectedIndex())).
                    getName();
            apellido = ((Persona) modeloLISTA.get(
                    jl_Males.getSelectedIndex())).
                    getApellido();
                    
            edad = ((Persona) modeloLISTA.get(
                    jl_Males.getSelectedIndex())).
                    getEdad();
            //nodo_seleccionado.add((MutableTreeNode) new Persona(nombre,nacionalidad,edad));
            
            int centinela = -1;
//            for (int i = 0; i < raiz.getChildCount(); i++) {
//                if (raiz.getChildAt(i).toString().
//                        equals(nombre)) {
//                    DefaultMutableTreeNode p
//                            = new DefaultMutableTreeNode(
//                                    new Persona(nombre,apellido,
//                                            nacionalidad, edad)
//                            );
//                    ((DefaultMutableTreeNode) nodo_seleccionado.getChildAt(i)).add(p);
//                    centinela = 1;
//                } //fin if
//            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(nombre);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Persona(nombre,apellido,
                                        nacionalidad, edad)
                        );
                n.add(p);
                nodo_seleccionado.add(n);
            }  // fin if          
            modeloARBOL.reload();

        } else if (jl_Females.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA1
                    = (DefaultListModel) jl_Females.getModel();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }

    }//GEN-LAST:event_jmi_AggPersonaActionPerformed

    private void jt_VocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_VocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_VocacionActionPerformed

    private void jt_NormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_NormalMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_Normal.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_Normal.setSelectionRow(row);
            Object v1
                    = jt_Normal.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            //nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getLevel() == 1) {
                this.Menu_Sex.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getLevel() == 2) {
                this.Menu_Personas.show(evt.getComponent(), evt.getX(), evt.getY());
            }else if(nodo_seleccionado.getLevel() == 3){
                this.Menu_mod_elim.show(evt.getComponent(), evt.getX(), evt.getY());
            }

//            } else if (nodo_seleccionado.getLevel() == 1) {
//                this.menu_Red_Leng.show(evt.getComponent(), evt.getX(), evt.getY());
//            } else if (nodo_seleccionado.getLevel() == 2) {
//                this.menu_modificar.show(evt.getComponent(), evt.getX(), evt.getY());
//            }
//            if (nodo_seleccionado.getUserObject() instanceof Pais) {
//                Pais_seleccionada
//                        = (Pais) nodo_seleccionado.
//                                getUserObject();
//                Menu_Personas.show(evt.getComponent(),
//                        evt.getX(), evt.getY());
//            }
//            else if (nodo_seleccionado.getUserObject() instanceof ) {
//                lenguaje_seleccionada
//                        = (Lenguaje) nodo_seleccionado.
//                                getUserObject();
//                menu_popup.show(evt.getComponent(),
//                        evt.getX(), evt.getY());
//            }
        }
    }//GEN-LAST:event_jt_NormalMouseClicked

    private void jmi_HombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_HombreMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        String sex = "Male";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();

    }//GEN-LAST:event_jmi_HombreMouseClicked

    private void jmi_MujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_MujerMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        String sex = "Female";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();
    }//GEN-LAST:event_jmi_MujerMouseClicked

    private void jmi_HombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_HombreActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        String sex = "Male";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();
    }//GEN-LAST:event_jmi_HombreActionPerformed

    private void jmi_MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_MujerActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        String sex = "Female";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();
    }//GEN-LAST:event_jmi_MujerActionPerformed

    private void Agg_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agg_PersonaActionPerformed
        // TODO add your handling code here:
        jd_createPerson.setModal(true);
        jd_createPerson.pack();
        jd_createPerson.setLocationRelativeTo(this);
        jd_createPerson.setVisible(true);
//        DefaultListModel modelo
//                = (DefaultListModel) jl_Males.getModel();
//        DefaultListModel modelo1
//                = (DefaultListModel) jl_Females.getModel();
//        int edad = Integer.parseInt(this.jt_Edad.getText());
//        String sex = "";
//        boolean titona = false;
//        }
//        //String nacionalidad, String name, String apellido, int edad, String genero, String vocacion, boolean tituloU, boolean virus
//        Persona x = new Persona(this.jt_Nacionalidad.getText(), this.jt_Name.getText(), this.jt_Apellido.getText(), edad, sex, this.jt_Vocacion.getText(),
//                title, corona);
//        if (sex.equals("male")) {
//            modelo.addElement(x);
//        } else {
//            modelo1.addElement(x);
//        }
//        this.jt_Apellido.setText("");
//        this.jt_Edad.setText("");
//        this.jt_Nacionalidad.setText("");
//        this.jt_Name.setText("");
//        this.jt_Vocacion.setText("");le = true;
//        boolean corona = true;
//        if (this.rb_Male.isSelected()) {
//            sex = "male";
//        } else {
//            sex = "female";
//        }
//        if (this.rb_TrueU.isSelected()) {
//            title = true;
//        } else {
//            title = false;
//        }
//        if (this.rb_TrueC.isSelected()) {
//            corona = true;
//        } else {
//            corona = false;
//        }
//        //String nacionalidad, String name, String apellido, int edad, String genero, String vocacion, boolean tituloU, boolean virus
//        Persona x = new Persona(this.jt_Nacionalidad.getText(), this.jt_Name.getText(), this.jt_Apellido.getText(), edad, sex, this.jt_Vocacion.getText(),
//                title, corona);
//        if (sex.equals("male")) {
//            modelo.addElement(x);
//        } else {
//            modelo1.addElement(x);
//        }
//        this.jt_Apellido.setText("");
//        this.jt_Edad.setText("");
//        this.jt_Nacionalidad.setText("");
//        this.jt_Name.setText("");
//        this.jt_Vocacion.setText("");

    }//GEN-LAST:event_Agg_PersonaActionPerformed

    private void jmi_ElimPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ElimPersonaActionPerformed
        // TODO add your handling code here:
         DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        DefaultMutableTreeNode padre = (DefaultMutableTreeNode) nodo_seleccionado.getParent();
        padre.remove(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_jmi_ElimPersonaActionPerformed

    private void jmi_ModPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ModPersonaActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_Normal.getModel();
        String lenguaje = JOptionPane.showInputDialog("Ingrese nombre nuevo");
        nodo_seleccionado.setUserObject(lenguaje);
        m.reload();
    }//GEN-LAST:event_jmi_ModPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    Color color;
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
    Pais Pais_seleccionada;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agg_Pais;
    private javax.swing.JMenuItem Agg_Persona;
    private javax.swing.ButtonGroup CoronaVirus;
    private javax.swing.JPopupMenu Menu_Personas;
    private javax.swing.JPopupMenu Menu_Sex;
    private javax.swing.JPopupMenu Menu_mod_elim;
    private javax.swing.JPanel PanelPais;
    private javax.swing.ButtonGroup Sex;
    private javax.swing.ButtonGroup TituloU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_AddTree_Pais;
    private javax.swing.JButton jb_AddTree_Persona;
    private javax.swing.JButton jb_Color;
    private javax.swing.JDialog jd_createPais;
    private javax.swing.JDialog jd_createPerson;
    private com.toedter.calendar.JDateChooser jdate_FechaFundacion;
    private javax.swing.JList<String> jl_Females;
    private javax.swing.JList<String> jl_Males;
    private javax.swing.JList<String> jl_Paises;
    private javax.swing.JMenuItem jmi_AggPersona;
    private javax.swing.JMenuItem jmi_ElimPersona;
    private javax.swing.JMenuItem jmi_Hombre;
    private javax.swing.JMenuItem jmi_ModPersona;
    private javax.swing.JMenuItem jmi_Mujer;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTree jt_Corona;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Nacionalidad;
    private javax.swing.JTextField jt_Name;
    private javax.swing.JTextField jt_NamePais;
    private javax.swing.JTree jt_Normal;
    private javax.swing.JTextField jt_Vocacion;
    private javax.swing.JTextField jt_nameHimno;
    private javax.swing.JRadioButton rb_FalseC;
    private javax.swing.JRadioButton rb_FalseU;
    private javax.swing.JRadioButton rb_Female;
    private javax.swing.JRadioButton rb_Male;
    private javax.swing.JRadioButton rb_TrueC;
    private javax.swing.JRadioButton rb_TrueU;
    // End of variables declaration//GEN-END:variables
}
